### ISSUE TITLE
[FEAT]: add docstring for all functions as comments and as in doc

### ISSUE THREAD

**Issue by lwaekfjlk** [ulab-uiuc/research-town#373]
### Description

need to use sphinx-apidoc to achieve auto link

**Comment by Monstertail** [comment]
[Refs]
1. [How to apply sphinx to generate API doc ](https://sphinx-apidoc.readthedocs.io/zh-cn/latest/)

**Comment by Monstertail** [comment]
[break down the issues to steps]
1. add Sphinx to project dependencies--see dependencies for Sphinx [here](https://iridescent.ink/HowToMakeDocs/Basic/Sphinx.html#what-is-sphinx);
2.

**Comment by lwaekfjlk** [comment]
@Kunlun-Zhu

**Comment by lwaekfjlk** [comment]
no need now.
