### ISSUE TITLE
[BUG]: Denpendencies not satisfied after poetry install

### ISSUE THREAD

**Issue by Kunlun-Zhu** [ulab-uiuc/research-town#517]
### Description of the bug

Denpendencies not satisfied after poetry install

### Steps To Reproduce

After I ```poetry install```
$ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: research_town (0.0.1)
(research_town) $ python examples/research_town_demo.py 
Traceback (most recent call last):
  File "GitHub\research-town\examples\research_town_demo.py", line 6, in <module>
    from research_town.dbs import AgentProfileDB, EnvLogDB, PaperProfileDB, ProgressDB
  File "GitHub\research-town\research_town\dbs\__init__.py", line 19, in <module>
    from .db_agent import AgentProfileDB
  File "GitHub\research-town\research_town\dbs\db_agent.py", line 3, in <module>
    from transformers import BertModel, BertTokenizer
ModuleNotFoundError: No module named 'transformers'
I run the python code from the example folder, and receiving an error about dependencies.

**Comment by Kunlun-Zhu** [comment]
From poetry install to running the example, I have install other package including:` lxml, bs4, pytorch, transformers`

**Comment by lwaekfjlk** [comment]
fixed in #655
