### ISSUE TITLE
[FEAT]: support faiss to enable efficient search

### ISSUE THREAD

**Issue by lwaekfjlk** [ulab-uiuc/research-town#715]
### Description

we should use faiss to accelerate

**Comment by shreypandey** [comment]
Hi @lwaekfjlk,
Is FAISS integration required for accelerated retrieval of agent and paper retrieval?
If so, perhaps it could be achieved with an embedding database like Redis and creating appropriate ANN indexes on embeddings in that, as suggested in as mentioned in #430 . 

Additionally, FAISS requires re-indexing whenever new embeddings are added, which could be managed asynchronously and more efficiently with an embedding database.

**Comment by lwaekfjlk** [comment]
yes, @shreypandey, good point! thanks for mentioning that, you can check https://github.com/ulab-uiuc/research-town/issues/431 that we include redis support in the 0.0.2 version. Looking forward to futher discussion.

**Comment by shreypandey** [comment]
Hi @lwaekfjlk, I have proposed an implementation of redis integration on #428, Please review the [proposed implementation](https://github.com/ulab-uiuc/research-town/issues/428#issuecomment-2408661256).

**Comment by lwaekfjlk** [comment]
sure.

**Comment by lwaekfjlk** [comment]
this should be squashed together into #428. therefore, close.
